import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { memo, useEffect } from 'react'
import { ThemeProvider } from '@material-ui/styles'
import { CssBaseline } from '@material-ui/core'

import { darkTheme } from '~/themes'

const App = memo<AppProps>(({ Component, pageProps }) => {
  useEffect(() => {
    document.querySelector('#jss-server-side')?.remove()
  }, [])

  return (
    <ThemeProvider theme={darkTheme}>
      <Head>
        <title>Conditional Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Component {...pageProps} />
    </ThemeProvider>
  )
})

export default App
