import type { NextPage } from 'next'
import Router from 'next/router'
import Head from 'next/head'
import { useEffect } from 'react'

const Home: NextPage = () => {
  useEffect(() => {
    Router.push('/auth/register')
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
